### ISSUE TITLE
Add `--version` flag

### ISSUE THREAD

**Issue by jtratner** [chanzuckerberg/miniwdl#121]
It'd be really nice to be able to do:

```
miniwdl --version
```

and have it dump at least cromwell and miniwdl version out to shell for use in bug reports. :)

Also could be nice to have shellcheck version but I'm less opinionated about that.

(hope it's useful to be putting up bug reports!)

**Comment by mlin** [comment]
I did this in a slightly cheesy way in v0.1.6 (shelling out to `pip3 show miniwdl`). The package tooling we're using, [pbr](https://docs.openstack.org/pbr/latest/), seems to make it surprisingly cumbersome to detect the package version at runtime without hard-coding it somewhere. I will come back to this.

Yes, please keep them coming :) Proactive evolution of the master branch will be a little slow for the next several weeks because we're working on the miniwdl-native WDL runner which is a large bolus of work of course. But I'm really happy to interrupt on any ideas or reports!
