### ISSUE TITLE
`available_inputs` does not match namespace in cromwell

### ISSUE THREAD

**Issue by DavyCats** [chanzuckerberg/miniwdl#193]
I was messing around with the WDL bindings and noticed the following:

In cromwell, defining inputs for subworkflows (or underlying tasks) requires you to mention both the call alias and the sub-workflow name in the namespace. In miniwdl, however, only the call alias is given as namespace in the `available_inputs` property of the workflow.
For example:
The input.json for cromwell might look something like this:
```JSON
{
  "test.message": "String",
  "test.conditional_call.SubWorkflow.task_call.optionalInput": "String? (optional)",
  "test.scattered_call.SubWorkflow.task_call.optionalInput": "String? (optional)"
}
```
miniwdl's `available_inputs` returns:
```
[scattered_call. [task_call. [optionalInput: String? optionalInput]], conditional_call. [task_call. [optionalInput: String? optionalInput]], message: String message]

# Or when turned into fully qualified namespaces:
test.scattered_call.task_call.optionalInput
test.conditional_call.task_call.optionalInput
test.message
```

Notice how `SubWorkflow` is missing. I tried to look into which is correct according to the WDL specs, but I couldn't find a clear answer. My question here is as follows: Should mininwdl comply with cromwell in this regard?

It would be rather trivial to "fix" this, at least for `available_inputs`, though it seems this may affect the run functionality as well.

---
<details>
<summary>
The workflow's which give these results.
</summary>
test.wdl:
<pre><code>
version 1.0

import "test2.wdl" as test2

workflow test {
   input {
       String message
   }

   if (true) {
       call test2.SubWorkflow as conditional_call {
           input:
               txt = message
       }
   }

   scatter (a in ["a"]) {
       call test2.SubWorkflow as scattered_call {
           input:
               txt = message
       }
   }

   parameter_meta {
       message: {discription:"Some text", default:"None"}
   }
}
</code></pre>

test2.wdl:
<pre><code>
version 1.0

workflow SubWorkflow {
    input {
        String txt = "hey"
    }

    call echo as say {
        input:
            txt=txt
    }

    parameter_meta {
        txt: ":p"
    }
}

task echo {
    input {
        String txt
        String? optionalInput
    }

    command {
        echo ~{txt}
        echo optional? ~{optionalInput}
    }

    parameter_meta {
        txt: "blah"
    }
}
</code></pre>
</details>

**Comment by DavyCats** [comment]
Oh and when I say it would be trivial to fix, I mean it can be fixed by changing this line:
https://github.com/chanzuckerberg/miniwdl/blob/ba068997a24006676e8f5a93dd3d381769218e73/WDL/Tree.py#L462

to this:
```python
            if isinstance(self.callee, Workflow):
                ans = [Env.Namespace("{}.{}".format(self.name, self.callee.name), ans)]
            else:
                ans = [Env.Namespace(self.name, ans)]
```

**Comment by mlin** [comment]
Thanks for reporting! Off the top of my head, I find it unexpected that the namespace behavior differs depending on whether the callee happens to be a task or sub-workflow. But it's not difficult to implement it that way as you say.

**Comment by mlin** [comment]
When we write a `call callee { input: ... }` inside a workflow, the same syntax applies whether the callee is a task or subworkflow, right? (TBC I'm not necessarily against snapping to the Cromwell JSON behavior -- I'm just trying to measure it up)

**Comment by DavyCats** [comment]
I agree that it is odd for this behaviour to differ between calling a task and a workflow. The call syntax doesn't differ at all between calling a sub-workflow or a task, as far as I'm aware.

**Comment by mlin** [comment]
Hi @DavyCats 

I started a discussion to clarify this on OpenWDL. Pending the outcome of that, my inclination is to keep `available_inputs` as-is, but enhance the miniwdl code responsible for reading Cromwell-style JSON so that it can accept, but not require, the workflow name in the JSON key for a subworkflow input. I haven't actually written the code for that yet though, so I'll have to see if that works out.

Also I wanted to give you a general heads-up that the next point release of miniwdl v0.4.0 this coming week will include a breaking rewrite of the `WDL.Env` module to improve its API. It will probably require some changes to wdl_aid. Sorry about this, but the old interface had some problems so I wanted to do one round of breaking changes before committing to API stability going forward (which we will be).

**Comment by DavyCats** [comment]
Thanks for the heads-up and sorry for the late response (I was on holiday). I will have a look at the changes as soon as I can find the time to do so.

**Comment by mlin** [comment]
To make the workaround idea more concrete,

If the input JSON has a key with three namespaces like,

```
    "wf.callname.subwf.x": "foo"
````

And we are not able to resolve `wf.callname.subwf.x` to an input declaration, at the point where we would otherwise throw an "invalid input" error, try to recover by deleting the third namespace, `wf.callname.x` and seeing if we can resolve that.

Since callname is necessarily unique, I don't see a case where this can lead to resolving the 'wrong' input declaration.
