### ISSUE TITLE
Add support for development version of WDL

### ISSUE THREAD

**Issue by jdidion** [chanzuckerberg/miniwdl#233]
Cromwell is able to execute WDL written using the development version ("version development"). Currently, miniwdl doesn't recognize "version development" and instead treats it as "draft-2". Instead, miniwdl should throw an exception or, preferably, add support for the new features in the development version.

**Comment by mlin** [comment]
@jdidion I think with "version development" it should at least [assume 1.0](https://github.com/chanzuckerberg/miniwdl/blob/34c442568a5c2898bc6d393dc7bd2b86879bb7d2/WDL/_parser.py#L774) rather than draft-2; are you seeing behavior contrary to that?

The development version is a moving target of course. Could you elaborate on which features you need most? Thx!

**Comment by jdidion** [comment]
This is not the case. See ca line 774 https://github.com/chanzuckerberg/miniwdl/blob/d9ed0b354e779c88f748e477cf8d780d163cc20f/WDL/_parser.py

**Comment by mlin** [comment]
Ah yea I stand corrected, here's a patch https://github.com/chanzuckerberg/miniwdl/commit/e3f2dbff8f4045eb4d84e07afa52a2b08e665cdb

I can cut a v0.4.1 release with this once we triage the other issues

**Comment by mlin** [comment]
v0.4.1 maintenance release should at least use the most up-to-date grammar available given `version development`. Please open new issues for any specific development-version features needed urgently. Thanks!
