### ISSUE TITLE
runner: configurable concurrency limit

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#244]
We've set up the parallel runner with a thread pool size of `multiprocessing.cpu_count()`, so that at most that many task calls can be running concurrently (the effective limit might be fewer, if individual tasks request multiple CPUs). This is a reasonable default, but users might wish to dial it up or down in specific circumstances.

Add an optional kwarg to `run_local_workflow` allowing caller to override the thread pool size. Also, [expose this as a `miniwdl run` command-line option](https://github.com/chanzuckerberg/miniwdl/blob/c69ef339c3391b598e619a41884dad1d88666dcd/WDL/CLI.py#L273), perhaps `-P` following gnu parallel.

**Comment by adamnovak** [comment]
Was the solution to this the `task_concurrency` key in the `[scheduler]` section of the config, which looks like it actually gives the number of CPU cores to schedule (and not the number of concurrent tasks to run)?

I'm wanting to limit a MiniWDL run to only half my machine's cores, and it looks like this issue is about doing that and that that config variable might be the solution, but it also isn't documented except as a workaround for misbehavior of the beta container backends and in the [example config](https://github.com/chanzuckerberg/miniwdl/blob/5ccead060fd3755df28d1e89d3d160eb7a5f3ee9/WDL/runtime/config_templates/default.cfg#L13-L19). I expected to find it when [searching the RtD docs](https://miniwdl.readthedocs.io/en/latest/search.html?q=task_concurrency&check_keywords=yes&area=default)
