### ISSUE TITLE
optional File? outputs from tasks

### ISSUE THREAD

**Issue by nh13** [chanzuckerberg/miniwdl#255]
Both `miniwdl check` and `miniwdl` run fail with the following reduced example.  See: https://github.com/openwdl/wdl/issues/20.  Looks like `dxWDL` and `Cromwell` support optional outputs.

```
miniwdl check optional_outputs.wdl 
(optional_outputs.wdl Ln 18 Col 35) Expected File instead of File?
                "some_optional_file": some_task.some_optional_file,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* Hint: for compatibility with older existing WDL code, try setting --no-quant-check to relax quantifier validation rules.
```

```
version 1.0
  

struct FooStruct {
    File some_required_file
    File? some_optional_file
}

workflow some_workflow {
    input {
        String file_name
    }
    output {
        FooStruct out = {
            "some_required_file": some_task.some_required_file,
            "some_optional_file": some_task.some_optional_file,
        }
    }
    call some_task  {
        input:
            file_name=file_name,
    }
}

task some_task {
    input {
        String file_name
    }
    output {
      File some_required_file = "~{file_name}.txt"
      File? some_optional_file = "~{file_name}.optional.txt"
    }
    command <<<
    echo "Hello World!" > ~{file_name}.txt;
    >>>
}
```

**Comment by mlin** [comment]
The particular error shown here is the same as https://github.com/chanzuckerberg/miniwdl/issues/256#issuecomment-540509766. However, it's also true that the miniwdl task runtime doesn't currently implement the https://github.com/openwdl/wdl/pull/310 behavior that a non-existent output filename successfully propagates to a null output value, which we should implement.

**Comment by mlin** [comment]
@nh13 

1. If you switch to the object literal for the struct, it should avoid the particular "Expected File instead of File?" error
2. If the task runs and does generate the `~{file_name}.optional.txt` file, I think it will work.
3. But currently if it doesn't generate that file intending for it to be a null output, I think the task runtime will throw a file not found error. 

The desired behavior in the last case will not be that difficult too implement (certainly easier than the type inference issues in #256), I can try to get to this shortly.
