### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#30]

**Comment by rhpvorderman** [comment]
@mlin 

This has now been made very easy for python packages
```
conda create -n conda-build conda-build
conda activate conda-build
conda skeleton pypi miniwdl
```

This will create a `miniwdl` folder with the `meta.yml` file in it.

Since Cromwell is already on conda-forge I recommend putting miniwdl on conda-forge as well. This has the advantage that conda-forge comes with an automated bot that will update the package as soon as there is a new package on pypi. All you have to do in that case is accept the pull request from the autoticker bot.

I could package it up and put it in conda-forge for you if you would like that.

**Comment by mlin** [comment]
@rhpvorderman Thank you for this info; it's super-helpful as I don't have previous experience with conda packaging. If you were to package it up, would I also be able to maintain it at future points in the event you wouldn't always be able to help so generously? If so then I'd be very grateful to take you up on the offer. Thanks again!

**Comment by rhpvorderman** [comment]
@mlin. Yes maintaining a package is much easier than adding one. I will add you as a maintainer. From that point on the package is almost automaintained by the autoupdate bot.

**Comment by rhpvorderman** [comment]
It is done and waiting to be merged:
https://github.com/conda-forge/staged-recipes/pull/8548

**Comment by mlin** [comment]
https://github.com/conda-forge/miniwdl-feedstock
