### ISSUE TITLE
ECS IAM role credential pass-through support

### ISSUE THREAD

**Issue by kislyuk** [chanzuckerberg/miniwdl#337]
When running miniwdl workflows in ECS task containers, we need a way to forward the AWS credential configuration to child containers spawned by miniwdl.

The following links describe the ECS IAM credential protocol:
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
* https://aws.amazon.com/blogs/compute/a-guide-to-locally-testing-containers-with-amazon-ecs-local-endpoints-and-docker-compose/

The cleanest way to accomplish this would be to configure the child containers to have the same connectivity to the ECS agent container as the parent container, and configure the ECS agent to recognize the child containers as eligible for the same IAM role crdentials as the parent container.

**Comment by kislyuk** [comment]
Here is a possible relatively clean way to do this:
- miniwdl exposes an API for event callbacks, including a `task-ready-to-start` callback
- miniwdl plugin starts a TCP tunnel using something like `ncat --listen --keep-open localhost 80 --sh-exec "ncat 169.254.170.2 80"`
- miniwdl plugin changes the network config for the child container to make port 80 routable between the child and parent
- miniwdl plugin changes the environment variables for the child container to include `AWS_CONTAINER_CREDENTIALS_FULL_URI=http://<PARENT_CONTAINER_IP>/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`

The effect of this is that the child container will be able to impersonate the parent (miniwdl) container while talking to the ECS agent to get its credentials.

**Comment by mlin** [comment]
@kislyuk here's a possible radical alternative; make miniwdl able to start a task using `subprocess.check_call()` avoiding docker entirely. I think this is what Cromwell actually does if you don't supply `runtime.docker` at all (whereas miniwdl right now defaults it to `ubuntu:18.04`). This "feature" potentially has broader utility anytime a developer is willing forego portability & isolation in order to interact with the host, so the effort would be more leveraged versus writing the plugin very customized to this case. How suitable this would be depends on the nature of the AWS operations we need to do, though. WDYT?

**Comment by kislyuk** [comment]
I'm not a huge fan of that approach, because it provides more opportunities for tasks to interfere with each other.

**Comment by mlin** [comment]
But surely you can see my calculation that it'd unblock many similar use cases in one stroke (other clouds, etc.), versus maintaining code to configure the following, dedicated to the scenario of running on ECS & needing to call AWS APIs from within task:

> - miniwdl plugin starts a TCP tunnel using something like `ncat --listen --keep-open localhost 80 --sh-exec "ncat 169.254.170.2 80"`
> - miniwdl plugin changes the network config for the child container to make port 80 routable between the child and parent
> - miniwdl plugin changes the environment variables for the child container to include `AWS_CONTAINER_CREDENTIALS_FULL_URI=http://<PARENT_CONTAINER_IP>/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`

I think the uncontainerized approach is suitable if the need to interact with AWS is just to transfer files or query/update metadata at the beginning & end of the workflow (so only those little tasks have the guardrails off). Less so if the use case is to stream big data from AWS for intensive streaming processing, since you want resource isolation for that. Where are we there?

**Comment by kislyuk** [comment]
I understand that uncontainerized execution is a useful and desirable feature. I agree that it would be useful, I just don't think it would satisfy my need here.

I have existing tasks that want to use AWS APIs in the middle of their execution, to call external data sources, stream data, and upload status updates that animate progress bars in the front-end. Over time I'd like to reduce the reliance on these, but some of them will remain legitimately needed.

At the same time I want to use the strong isolation guarantees that containers provide; I don't want to run these tasks uncontained, given the history of bugs from adverse interactions between tasks.

As I mentioned offline, I'd be happy to implement the custom logic myself if miniwdl can provide an event subscription/callback API for plugins that want to customize I/O and task management behaviors.

**Comment by mlin** [comment]
OK -- that's helpful context.

**Comment by mlin** [comment]
@kislyuk reading docs about docker's default bridge network [1,2], I'm tempted to conclude that no config override is needed to allow TCP connections between two containers running on the same host. Do you think this is true in our case, i.e. do you or ECS disable/change Docker's default bridge network?

If indeed the default bridge network applies, then I suggest we just start the `ncat --listen --keep-open ... &` as a background process from inside the manager container before running miniwdl. (Of course it could be started by a miniwdl task plugin, but then we need to make sure we only start one.) Then a plugin in miniwdl can prepend to the task command,

```
f"export AWS_CONTAINER_CREDENTIALS_FULL_URI='http://{socket.gethostbyname(socket.gethostname())}/{os.environ["AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"]}'\n\n"
```

The [omnibus example](https://github.com/chanzuckerberg/miniwdl/tree/master/examples/plugin_task_omnibus) shows how to manipulate the command in this way. WDYT?

(To be clear it **is** possible for a plugin to manipulate a task container's network configuration, but if we don't need to then so much the better, of course.)

[1] https://docs.docker.com/network/bridge/
[2] https://docs.docker.com/network/network-tutorial-standalone/

**Comment by mlin** [comment]
Also, if a configuration option saying "set the following environment variables in all task containers" would remove the need for a plugin entirely, that would be an easy and reasonable feature to add (with appropriate portability warnings) in the next minor version.
