### ISSUE TITLE
call caching: input/output file coherence

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#402]
A call cache entry should be invalidated if, upon lookup, any files referenced by the inputs and outputs aren't the same ones present when the entry was created.

On the local filesystem, we can compare the modification timestamps (mtimes) between the cache JSON file and the referenced files to ask if any of them are newer (or have been deleted). The helper function [`WDL.Value.rewrite_env_files()`](https://miniwdl.readthedocs.io/en/latest/WDL.html#WDL.Value.rewrite_env_files) could be used to generate the list of filenames referenced in an inputs or outputs Env. (It's meant for another purpose, rewriting all the filenames, but we could just give it a lambda that builds up the list by side-effect)

In the future, we may need to support querying cloud storage for timestamps, or storing+checking file content hashes ([recent Cromwell discussion](https://github.com/broadinstitute/cromwell/pull/5450)). We don't need to implement these immediately, but we should design the mechanism to accommodate future elaborations like that.

**Comment by mlin** [comment]
@MDunitz @illusional interest

**Comment by illusional** [comment]
Thanks for the tag! From what I understand, the GCS and S3 content ids are always unique as bucket storage doesn't usually allow mutations, however local file systems do not have the same requirement hence the cromwell discussion. Interested to follow this through.

**Comment by mlin** [comment]
Note to selves: the filenames in miniwdl's output JSON are sometimes symbolic links to the actual files. In that case we should be looking at the newer of the mtimes for link and target. Content hashes would be on the target.

**Comment by rhpvorderman** [comment]
Good news: xxhash is also available for python: https://pypi.org/project/xxhash/.

This particular library is hashlib compliant. If content hashing were to be implemented, I would strongly suggests only implementing xxhash, and leave out any cryptographic hashes (such as md5 and sha256). 

Another observation that might help: md5sum on the command line uses a buffer size of 4096 or 8192 bytes. In python you can use a larger buffer size, and that way be faster such as used here https://github.com/LUMC/pytest-workflow/blob/d7e67535341a6cd980f9793449fc339b5b0f472d/src/pytest_workflow/file_tests.py#L146.

That's why in Cromwell a buffer size of 128K is used. (After that dimishing returns hit quickly, and I suspect that python can make do with 64K as it is less bloated than java).
