### ISSUE TITLE
miniWDL fails to complete self test

### ISSUE THREAD

**Issue by hseabolt** [chanzuckerberg/miniwdl#519]
Installed miniwdl using conda inside a fresh conda environment, and have root access to Docker.
When testing run_self_test, miniwdl fails and returns errors that appear to be related to Docker?

Log file attached.
[miniwdl_run_self_test.log](https://github.com/chanzuckerberg/miniwdl/files/7108079/miniwdl_run_self_test.log)

**Comment by mlin** [comment]
@hseabolt Thanks for the log; it seems to indicate that for some reason Docker is having difficulty pulling a specific, public image that miniwdl uses internally. Can you please try at your terminal,

```
docker run --rm -it ghcr.io/chanzuckerberg/miniwdl_tools:Id_sha256_ad9e362d2de002f2128f52cf5961831dbeed944637f347df69df814dc8cfa349 cat /etc/issue
```

which is the same image it's trying to pull (it should just print `Ubuntu 20.04.2 LTS`). Wondering if we get a more-specific error message about what difficulty Docker is experiencing with that image (or if it works, possibly the problem was temporary)

**Comment by dbtara** [comment]
@mlin   Do you know if accessing the containers requires us to setup PAT and auth?  could the failure to configure the auth causing this issue?

**Comment by hseabolt** [comment]
@mlin It seems like there is some auth error against ghrc?

```
Unable to find image 'ghcr.io/chanzuckerberg/miniwdl_tools:Id_sha256_ad9e362d2de002f2128f52cf5961831dbeed944637f347df69df814dc8cfa349' locally
docker: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable.
```

**Comment by mlin** [comment]
[The image is public](https://github.com/orgs/chanzuckerberg/packages/container/miniwdl_tools/5710806?tag=Id_sha256_ad9e362d2de002f2128f52cf5961831dbeed944637f347df69df814dc8cfa349) and shouldn't require any form of login or token to `docker pull`. Is it possible there's some sort of proxy/firewall on the route that could be interfering?

**Comment by mlin** [comment]
Closing as stale but do reopen if we can help further!
