### ISSUE TITLE
miniwdl cannot execute multiqc tasks with many reports due to ARG_MAX

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#592]
[MultiQC](https://github.com/ewels/multiqc) is a report aggregator for bioinformatics applications. As such it is one of the most useful applications in bioinformatics.

Unfortunately when aggregating a lot of reports, miniwdl chokes on the output. This is due to the mounting of each individual report in the container. This results in a very long command line argument that surpasses the ARG_MAX constraint imposed by the linux kernel.

As a possible workaround I tried `copy_input_files_for = ["multiqcTask"]` in the `file_io` section. Since all reports are typically small unlike NGS data files, copying isn't much effort. The reports are all put nicely in one folder. Unfortunately miniwdl then still proceeds to mount each file individually resulting in the crash.

A solution would be if miniwdl would just mount the folder instead. This has no security hazards as miniwdl just created the folder and made sure only necessary inputs are contained in it. Is this the best solution? Or do you have some other ideas on how to tackle this problem?

**Comment by mlin** [comment]
@rhpvorderman can you please clarify which invocation is overflowing? Is it in our `SubprocessBase` base class for singularity/udocker/podman? or the task command itself?

I thought you were on the right track with trying `copy_input_files_for`, because indeed that is supposed to have the side-effect of not needing to mount each input file individually (in [this if statement](https://github.com/chanzuckerberg/miniwdl/blob/3b04f0c1bccb86a5d0a36735e5a6fa7c11d66e04/WDL/runtime/backend/cli_subprocess.py#L166)). However something could be going wrong, or it could be a related problem downstream of that.

The AWS plugin uses a different strategy in which every container mounts the entire shared filesystem, and we just put symlinks in the task folder to the original input files. This is primarily because the AWS API doesn't make it convenient to mount specific files individually, but also avoids this problem. However, it also widely opens the backdoor for a WDL task to snoop or interfere with stuff it isn't meant to.

**Comment by rhpvorderman** [comment]
> I thought you were on the right track with trying copy_input_files_for, because indeed that is supposed to have the side-effect of not needing to mount each input file individually (in [this if statement](https://github.com/chanzuckerberg/miniwdl/blob/3b04f0c1bccb86a5d0a36735e5a6fa7c11d66e04/WDL/runtime/backend/cli_subprocess.py#L166)). However something could be going wrong, or it could be a related problem downstream of that.

I did verify again and in in `work/_miniwdl_inputs/0/` I see all the input files listed. So that part is going correctly. I should take a look at the code to see where it goes wrong.

> @rhpvorderman can you please clarify which invocation is overflowing? Is it in our SubprocessBase base class for singularity/udocker/podman? or the task command itself?

I find it hard to answer this question precisely. but let me try. I think the subprocessBase calls a process 'bash -l' that executes whatever `_run_invocation`. This bash script fails.
For more clarity I have added all the logs.

```
[scheduler]
container_backend=slurm_singularity
task_concurrency=200

[singularity]
run_options = [
        "--containall"
    ]
image_cache = "$PWD/.miniwdl/singularity_cache"

[file_io]
allow_any_input=true
copy_input_files_for = ["multiqcTask"]

[call_cache]
put = true 
get = true 
dir = "$PWD/miniwdl_call_cache"
```
[task.log](https://github.com/chanzuckerberg/miniwdl/files/9379817/task.log)
[singularity.log.txt](https://github.com/chanzuckerberg/miniwdl/files/9379820/singularity.log.txt)

**Comment by rhpvorderman** [comment]
It was a "BetweenKeyboardAndChairError" I had used the name of the task as aliased in the workflow `multiqcTask` while miniwdl uses the actual name of the task in task declaration `MultiQC` to determine whether inputs should be copied. My bad.
After changing this, it works as expected! 
Thanks for your help again!
