### ISSUE TITLE
`miniwdl check` dies on command containing `# ~{}`

### ISSUE THREAD

**Issue by wholtz** [chanzuckerberg/miniwdl#595]
```bash
$ miniwdl --version
miniwdl v1.7.0
$ cat bad_comment.wdl 
version 1.0
    
task dummy_task {
  input {
    String image
  }
    
  command  <<<
     # ~{}
    echo 'Hello World!'
  >>>
    
  runtime {
    docker: image 
  }
}
$ miniwdl check bad_comment.wdl
(bad_comment.wdl Ln 9 Col 8) Unexpected token Token('COMMAND2_FRAGMENT', "}\n    echo 'Hello World!'\n  ") at line 9, column 8.
Expected one of: 
	* /'/
	* SEP
	* SIGNED_INT
	* CNAME
	* LBRACE
	* LSQB
	* INT
	* SIGNED_FLOAT
	* LPAR
	* FALSE
	* DEFAULT
	* TRUE
	* OBJECT
	* IF
	* /"/
	* BANG
	* FLOAT
Previous tokens: [Token('__ANON_10', '~{')]

       # ~{}
           ^
```

I expected that `miniwdl check` would ignore comment contents and this task would pass.

**Comment by mlin** [comment]
Hi @wholtz is this behavior different from another WDL engine you've tried?

Our parser is treating the `command <<< >>>` section as one long string with interspersed interpolations. The `#` line is just part of the string and doesn't "become" a comment until bash reads the command at runtime. So the interpolation is still evaluated before that.

By analogy, if I enter at my bash terminal,

```bash
$ echo "# $(bogus)"
```

I get `-bash: bogus: command not found` because the interpolation is evaluated before anything parses the string.

On first impression I think this is expected behavior, but open to feedback.
