### ISSUE TITLE
Make sudo podman configurable

### ISSUE THREAD

**Issue by multimeric** [chanzuckerberg/miniwdl#619]
It seems that the current, unconfigurable behaviour is to use `sudo podman` always:https://github.com/chanzuckerberg/miniwdl/blob/7243c3907f5cc01d6e9f98faf5cd1e15ba9b4fa1/WDL/runtime/backend/podman.py#L23-L24

I'm on a system where I don't have root, which is actually why I installed podman in the first place. I would like to add a configuration option to never use sudo for podman. Or perhaps even better, to just remove `sudo` from the invocation always, because it should always be possible to just grant the current user permission to run it.

**Comment by mlin** [comment]
@multimeric Can you please elaborate more on the podman configuration to run it without sudo?

In default podman installations, being able to start podman containers is almost like having root access to the host, because e.g. you can mount any host file/directory into the container and then do anything to it. In that case, there's little point to configuring a user account such that it cannot sudo, but can podman.

There are other ways to set up podman in a more restricted way, but they're a little gnarly, and Singularity or udocker are more commonly used for that case. That's why we didn't cover the non-sudo podman case in the initial implementation. It's certainly possible, but I'm just trying to understand the configuration you're working with and how [a]typical it is. Thanks

**Comment by multimeric** [comment]
I'm not sure how new a development this is, but podman now supports an unprivileged installation on Linux: https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md. In addition to this, the default `brew` installation of podman on MacOS is also unprivileged, I assume because it uses a VM inside of which it can act as root: https://podman.io/getting-started/installation. 

So in both of these cases we have a podman installation where `sudo` is not needed. In some cases, such as my installation, the user actually doesn't even have the permission to use `sudo`, so it's actually imperative that miniWDL can use podman without sudo.

Thus, I'd like to add a config option that removes `sudo` from the podman invocations.

**Comment by mlin** [comment]
@multimeric couple quick questions about rootless podman...do the process(es) *inside* the container believe they're running as root, or as the invoking user id? if they create files in a mounted host directory, are those files root-owned or user-owned, after the container exits?

**Comment by multimeric** [comment]
I think it uses user namespaces, so the processes inside the container believe they are root or some other ID which maps to a real user ID outside of the container which is not root: https://opensource.com/article/19/2/how-does-rootless-podman-work. This goes the same for the files they create. If UID 1 inside the container maps to UID 100000 outside of the container, then the files they create will be owned by UID 100000.

**Comment by multimeric** [comment]
Thanks for this fix, it works great! For future users, I basically did this to get miniWDL working on MacOS without root:

```bash
pip install miniwdl
brew install podman
podman machine init --image-path stable
podman machine start
```
Then I set up my config file (`~/.config/miniwdl.cfg`):
```
[scheduler]
container_backend = podman

[podman]
exe = ["podman"]

[file_io]
chown = false
```

Then `miniwdl run` worked perfectly!
