### ISSUE TITLE
Run_self_test fails to download files

### ISSUE THREAD

**Issue by erikwolfsohn** [chanzuckerberg/miniwdl#689]
[miniwdl_run_self_test.log](https://github.com/user-attachments/files/15566940/miniwdl_run_self_test.log)

I've attached the logfile. The errors seem to indicate an issue with the docker installation, but testing with `docker run hello-world` works, so I don't think there's any issue with the environment. Running on Ubuntu Server 20.04, miniWDL was installed via conda and docker was installed via the apt repository.

Thanks for your help, let me know if I can provide any more information!

**Comment by mlin** [comment]
@erikwolfsohn The curious thing I see in your log is an error message referring to `/var/snap/docker` when you mentioned having installed docker via apt rather than snap. Perhaps the docker snap is *also* installed and they're conflicting in some way? I found this discussion:

https://www.reddit.com/r/docker/comments/shztqs/wow_docker_works_a_lot_better_when_you_dont_have/

HTH

**Comment by erikwolfsohn** [comment]
That was the issue! Thank you so much for your help!
